import type { UIDocument } from "@/types/ui-document";

export const mockRecentDocuments: UIDocument[] = [
  {
    id: "rec-001",
    name: "Q4 Financial Report 2025.xlsx",
    type: "spreadsheet",
    size: 2456789,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    createdAt: "2025-12-15T09:00:00Z",
    updatedAt: "2026-01-14T14:30:00Z",
    accessedAt: "2026-01-14T16:45:00Z",
    createdBy: {
      id: "user-001",
      name: "John Smith",
      email: "john.smith@company.com",
    },
    updatedBy: {
      id: "user-001",
      name: "John Smith",
      email: "john.smith@company.com",
    },
    path: "/Finance/Reports/2025",
    status: "published",
    version: "3.2",
    isStarred: true,
    isLocked: false,
    tags: ["finance", "quarterly", "report"],
    permissions: ["read", "write", "delete"],
  },
  {
    id: "rec-002",
    name: "Project Roadmap 2026.pptx",
    type: "presentation",
    size: 8765432,
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-01-14T11:20:00Z",
    accessedAt: "2026-01-14T15:30:00Z",
    createdBy: {
      id: "user-002",
      name: "Sarah Johnson",
      email: "sarah.j@company.com",
    },
    updatedBy: {
      id: "user-002",
      name: "Sarah Johnson",
      email: "sarah.j@company.com",
    },
    path: "/Projects/Planning",
    status: "published",
    version: "2.0",
    isStarred: false,
    isLocked: false,
    tags: ["roadmap", "planning", "2026"],
    permissions: ["read", "write"],
  },
  {
    id: "rec-003",
    name: "Employee Handbook v5.pdf",
    type: "pdf",
    size: 3456789,
    mimeType: "application/pdf",
    createdAt: "2025-06-01T08:00:00Z",
    updatedAt: "2026-01-10T09:15:00Z",
    accessedAt: "2026-01-14T14:00:00Z",
    createdBy: {
      id: "user-003",
      name: "HR Department",
      email: "hr@company.com",
    },
    updatedBy: {
      id: "user-003",
      name: "HR Department",
      email: "hr@company.com",
    },
    path: "/HR/Policies",
    status: "published",
    version: "5.0",
    isStarred: false,
    isLocked: true,
    tags: ["hr", "policy", "handbook"],
    permissions: ["read"],
  },
  {
    id: "rec-004",
    name: "API Documentation.md",
    type: "document",
    size: 125678,
    mimeType: "text/markdown",
    createdAt: "2025-11-20T14:00:00Z",
    updatedAt: "2026-01-13T16:45:00Z",
    accessedAt: "2026-01-14T12:30:00Z",
    createdBy: {
      id: "user-004",
      name: "Dev Team",
      email: "dev@company.com",
    },
    updatedBy: {
      id: "user-005",
      name: "Mike Chen",
      email: "mike.c@company.com",
    },
    path: "/Engineering/Documentation",
    status: "draft",
    version: "4.1",
    isStarred: true,
    isLocked: false,
    tags: ["api", "docs", "technical"],
    permissions: ["read", "write", "delete"],
  },
  {
    id: "rec-005",
    name: "Brand Guidelines 2026.pdf",
    type: "pdf",
    size: 15678900,
    mimeType: "application/pdf",
    createdAt: "2026-01-05T11:00:00Z",
    updatedAt: "2026-01-12T10:30:00Z",
    accessedAt: "2026-01-14T11:00:00Z",
    createdBy: {
      id: "user-006",
      name: "Marketing Team",
      email: "marketing@company.com",
    },
    updatedBy: {
      id: "user-006",
      name: "Marketing Team",
      email: "marketing@company.com",
    },
    path: "/Marketing/Brand",
    status: "published",
    version: "1.0",
    isStarred: false,
    isLocked: false,
    tags: ["brand", "guidelines", "design"],
    permissions: ["read"],
  },
  {
    id: "rec-006",
    name: "Meeting Notes - Sprint 42.docx",
    type: "document",
    size: 45678,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    createdAt: "2026-01-13T15:00:00Z",
    updatedAt: "2026-01-13T17:30:00Z",
    accessedAt: "2026-01-14T09:00:00Z",
    createdBy: {
      id: "user-007",
      name: "Emily Davis",
      email: "emily.d@company.com",
    },
    updatedBy: {
      id: "user-007",
      name: "Emily Davis",
      email: "emily.d@company.com",
    },
    path: "/Projects/Sprints",
    status: "draft",
    version: "1.0",
    isStarred: false,
    isLocked: false,
    tags: ["meeting", "sprint", "notes"],
    permissions: ["read", "write"],
  },
  {
    id: "rec-007",
    name: "Contract Template.docx",
    type: "document",
    size: 89012,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    createdAt: "2025-08-15T10:00:00Z",
    updatedAt: "2025-12-20T14:00:00Z",
    accessedAt: "2026-01-13T16:00:00Z",
    createdBy: {
      id: "user-008",
      name: "Legal Team",
      email: "legal@company.com",
    },
    updatedBy: {
      id: "user-008",
      name: "Legal Team",
      email: "legal@company.com",
    },
    path: "/Legal/Templates",
    status: "published",
    version: "3.0",
    isStarred: true,
    isLocked: true,
    tags: ["legal", "contract", "template"],
    permissions: ["read"],
  },
  {
    id: "rec-008",
    name: "Server Architecture Diagram.png",
    type: "image",
    size: 567890,
    mimeType: "image/png",
    createdAt: "2025-10-10T09:00:00Z",
    updatedAt: "2026-01-08T11:00:00Z",
    accessedAt: "2026-01-13T14:30:00Z",
    createdBy: {
      id: "user-004",
      name: "Dev Team",
      email: "dev@company.com",
    },
    updatedBy: {
      id: "user-009",
      name: "Alex Turner",
      email: "alex.t@company.com",
    },
    path: "/Engineering/Architecture",
    status: "published",
    version: "2.1",
    isStarred: false,
    isLocked: false,
    tags: ["architecture", "diagram", "infrastructure"],
    permissions: ["read", "write"],
  },
];
