import type { SharedUIDocument } from "@/types/ui-document";

export type { SharedUIDocument as SharedDocument };

export const mockSharedDocuments: SharedUIDocument[] = [
  {
    id: "shared-001",
    name: "Product Launch Strategy.pptx",
    type: "presentation",
    size: 12345678,
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    createdAt: "2026-01-05T10:00:00Z",
    updatedAt: "2026-01-13T15:30:00Z",
    accessedAt: "2026-01-14T09:00:00Z",
    createdBy: {
      id: "user-010",
      name: "Rachel Green",
      email: "rachel.g@company.com",
    },
    updatedBy: {
      id: "user-010",
      name: "Rachel Green",
      email: "rachel.g@company.com",
    },
    path: "/Marketing/Campaigns",
    status: "draft",
    version: "2.3",
    isStarred: true,
    isLocked: false,
    tags: ["launch", "strategy", "marketing"],
    permissions: ["read", "write"],
    sharedBy: {
      id: "user-010",
      name: "Rachel Green",
      email: "rachel.g@company.com",
    },
    sharedAt: "2026-01-10T14:00:00Z",
    sharePermission: "edit",
  },
  {
    id: "shared-002",
    name: "Budget Forecast Q1 2026.xlsx",
    type: "spreadsheet",
    size: 1567890,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    createdAt: "2025-12-20T09:00:00Z",
    updatedAt: "2026-01-12T11:00:00Z",
    accessedAt: "2026-01-13T16:00:00Z",
    createdBy: {
      id: "user-011",
      name: "Tom Wilson",
      email: "tom.w@company.com",
    },
    updatedBy: {
      id: "user-011",
      name: "Tom Wilson",
      email: "tom.w@company.com",
    },
    path: "/Finance/Budgets",
    status: "published",
    version: "1.5",
    isStarred: false,
    isLocked: false,
    tags: ["budget", "forecast", "finance"],
    permissions: ["read"],
    sharedBy: {
      id: "user-011",
      name: "Tom Wilson",
      email: "tom.w@company.com",
    },
    sharedAt: "2026-01-08T10:30:00Z",
    sharePermission: "view",
    expiresAt: "2026-02-08T10:30:00Z",
  },
  {
    id: "shared-003",
    name: "Design System Components.fig",
    type: "other",
    size: 45678901,
    mimeType: "application/octet-stream",
    createdAt: "2025-09-15T14:00:00Z",
    updatedAt: "2026-01-11T16:45:00Z",
    accessedAt: "2026-01-14T10:30:00Z",
    createdBy: {
      id: "user-012",
      name: "Lisa Park",
      email: "lisa.p@company.com",
    },
    updatedBy: {
      id: "user-012",
      name: "Lisa Park",
      email: "lisa.p@company.com",
    },
    path: "/Design/Systems",
    status: "published",
    version: "4.0",
    isStarred: true,
    isLocked: false,
    tags: ["design", "components", "figma"],
    permissions: ["read", "write"],
    sharedBy: {
      id: "user-012",
      name: "Lisa Park",
      email: "lisa.p@company.com",
    },
    sharedAt: "2026-01-06T09:00:00Z",
    sharePermission: "edit",
  },
  {
    id: "shared-004",
    name: "Security Audit Report.pdf",
    type: "pdf",
    size: 2345678,
    mimeType: "application/pdf",
    createdAt: "2026-01-03T08:00:00Z",
    updatedAt: "2026-01-10T14:00:00Z",
    accessedAt: "2026-01-12T11:00:00Z",
    createdBy: {
      id: "user-013",
      name: "Security Team",
      email: "security@company.com",
    },
    updatedBy: {
      id: "user-013",
      name: "Security Team",
      email: "security@company.com",
    },
    path: "/IT/Security",
    status: "published",
    version: "1.0",
    isStarred: false,
    isLocked: true,
    tags: ["security", "audit", "compliance"],
    permissions: ["read"],
    sharedBy: {
      id: "user-013",
      name: "Security Team",
      email: "security@company.com",
    },
    sharedAt: "2026-01-10T15:00:00Z",
    sharePermission: "view",
  },
  {
    id: "shared-005",
    name: "Team Building Event Plan.docx",
    type: "document",
    size: 234567,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    createdAt: "2026-01-08T11:00:00Z",
    updatedAt: "2026-01-13T10:00:00Z",
    accessedAt: "2026-01-14T08:00:00Z",
    createdBy: {
      id: "user-014",
      name: "HR Events",
      email: "hr.events@company.com",
    },
    updatedBy: {
      id: "user-014",
      name: "HR Events",
      email: "hr.events@company.com",
    },
    path: "/HR/Events",
    status: "draft",
    version: "1.2",
    isStarred: false,
    isLocked: false,
    tags: ["event", "team", "planning"],
    permissions: ["read", "write"],
    sharedBy: {
      id: "user-014",
      name: "HR Events",
      email: "hr.events@company.com",
    },
    sharedAt: "2026-01-12T09:00:00Z",
    sharePermission: "comment",
  },
  {
    id: "shared-006",
    name: "Customer Feedback Analysis.xlsx",
    type: "spreadsheet",
    size: 3456789,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2026-01-09T13:30:00Z",
    accessedAt: "2026-01-11T15:00:00Z",
    createdBy: {
      id: "user-015",
      name: "Customer Success",
      email: "cs@company.com",
    },
    updatedBy: {
      id: "user-015",
      name: "Customer Success",
      email: "cs@company.com",
    },
    path: "/Customer/Analytics",
    status: "published",
    version: "2.0",
    isStarred: false,
    isLocked: false,
    tags: ["feedback", "analysis", "customers"],
    permissions: ["read"],
    sharedBy: {
      id: "user-015",
      name: "Customer Success",
      email: "cs@company.com",
    },
    sharedAt: "2026-01-09T14:00:00Z",
    sharePermission: "view",
  },
  {
    id: "shared-007",
    name: "Infrastructure Migration Plan.md",
    type: "document",
    size: 156789,
    mimeType: "text/markdown",
    createdAt: "2025-11-25T09:00:00Z",
    updatedAt: "2026-01-14T08:00:00Z",
    accessedAt: "2026-01-14T12:00:00Z",
    createdBy: {
      id: "user-016",
      name: "DevOps Team",
      email: "devops@company.com",
    },
    updatedBy: {
      id: "user-016",
      name: "DevOps Team",
      email: "devops@company.com",
    },
    path: "/Engineering/Infrastructure",
    status: "draft",
    version: "3.1",
    isStarred: true,
    isLocked: false,
    tags: ["migration", "infrastructure", "devops"],
    permissions: ["read", "write"],
    sharedBy: {
      id: "user-016",
      name: "DevOps Team",
      email: "devops@company.com",
    },
    sharedAt: "2026-01-07T11:00:00Z",
    sharePermission: "edit",
  },
];
