import type { Document, User } from "@/schemas";

const mockUsers: User[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john.doe@company.com",
    avatar: undefined,
    role: "admin",
  },
  {
    id: "user-2",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    avatar: undefined,
    role: "editor",
  },
  {
    id: "user-3",
    name: "Mike Wilson",
    email: "mike.wilson@company.com",
    avatar: undefined,
    role: "viewer",
  },
];

export const mockStarredDocuments: Document[] = [
  {
    id: "starred-1",
    objectId: "0900000180002001",
    name: "Company Strategy 2026.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    extension: "pdf",
    size: 4521984,
    status: "published",
    metadata: {
      title: "Company Strategy 2026",
      description: "Annual strategic roadmap and objectives",
      tags: ["strategy", "planning", "2026", "confidential"],
      category: "Executive",
    },
    folderId: "folder-exec",
    folderPath: "/Executive/Strategy",
    owner: mockUsers[0],
    createdAt: "2025-11-01T09:00:00Z",
    createdBy: mockUsers[0],
    updatedAt: "2026-01-08T15:30:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 4,
    isLocked: false,
    checkoutCount: 12,
    downloadCount: 89,
  },
  {
    id: "starred-2",
    objectId: "0900000180002002",
    name: "Product Roadmap Q1-Q2.xlsx",
    type: "spreadsheet",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    extension: "xlsx",
    size: 1245678,
    status: "approved",
    metadata: {
      title: "Product Roadmap Q1-Q2 2026",
      description: "Feature timeline and release schedule",
      tags: ["product", "roadmap", "planning"],
      category: "Product",
    },
    folderId: "folder-product",
    folderPath: "/Product/Roadmaps",
    owner: mockUsers[1],
    createdAt: "2025-12-10T14:00:00Z",
    createdBy: mockUsers[1],
    updatedAt: "2026-01-12T09:15:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 7,
    isLocked: true,
    lockedBy: mockUsers[1],
    lockedAt: "2026-01-12T09:15:00Z",
    checkoutCount: 23,
    downloadCount: 156,
  },
  {
    id: "starred-3",
    objectId: "0900000180002003",
    name: "API Documentation v3.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    extension: "docx",
    size: 892345,
    status: "published",
    metadata: {
      title: "API Documentation v3",
      description: "Complete REST API reference guide",
      tags: ["api", "documentation", "technical"],
      category: "Engineering",
    },
    folderId: "folder-eng",
    folderPath: "/Engineering/Documentation",
    owner: mockUsers[2],
    createdAt: "2025-08-15T11:30:00Z",
    createdBy: mockUsers[2],
    updatedAt: "2025-12-20T16:45:00Z",
    updatedBy: mockUsers[2],
    currentVersion: 12,
    isLocked: false,
    checkoutCount: 45,
    downloadCount: 312,
  },
  {
    id: "starred-4",
    objectId: "0900000180002004",
    name: "Brand Assets Package.zip",
    type: "archive",
    mimeType: "application/zip",
    extension: "zip",
    size: 156789012,
    status: "published",
    metadata: {
      title: "Brand Assets Package",
      description: "Complete brand kit with logos, fonts, and guidelines",
      tags: ["brand", "assets", "marketing", "design"],
      category: "Marketing",
    },
    folderId: "folder-marketing",
    folderPath: "/Marketing/Brand",
    owner: mockUsers[1],
    createdAt: "2025-06-01T10:00:00Z",
    createdBy: mockUsers[1],
    updatedAt: "2025-11-15T14:20:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 3,
    isLocked: false,
    checkoutCount: 8,
    downloadCount: 234,
  },
  {
    id: "starred-5",
    objectId: "0900000180002005",
    name: "Quarterly Sales Report.pptx",
    type: "presentation",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    extension: "pptx",
    size: 12456789,
    status: "approved",
    metadata: {
      title: "Q4 2025 Sales Report",
      description: "Quarterly sales performance and analysis",
      tags: ["sales", "report", "Q4", "2025"],
      category: "Sales",
    },
    folderId: "folder-sales",
    folderPath: "/Sales/Reports/2025",
    owner: mockUsers[0],
    createdAt: "2025-12-28T08:00:00Z",
    createdBy: mockUsers[0],
    updatedAt: "2026-01-05T17:30:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 2,
    isLocked: false,
    checkoutCount: 6,
    downloadCount: 45,
  },
  {
    id: "starred-6",
    objectId: "0900000180002006",
    name: "Team Photo - Annual Retreat.jpg",
    type: "image",
    mimeType: "image/jpeg",
    extension: "jpg",
    size: 8765432,
    status: "published",
    metadata: {
      title: "Team Photo - Annual Retreat 2025",
      description: "Company team photo from the annual retreat",
      tags: ["team", "photo", "event", "2025"],
      category: "Culture",
    },
    folderId: "folder-culture",
    folderPath: "/Culture/Events/2025",
    owner: mockUsers[2],
    createdAt: "2025-10-20T16:00:00Z",
    createdBy: mockUsers[2],
    updatedAt: "2025-10-20T16:00:00Z",
    updatedBy: mockUsers[2],
    currentVersion: 1,
    isLocked: false,
    checkoutCount: 0,
    downloadCount: 67,
  },
  {
    id: "starred-7",
    objectId: "0900000180002007",
    name: "Security Compliance Checklist.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    extension: "pdf",
    size: 567890,
    status: "published",
    metadata: {
      title: "Security Compliance Checklist",
      description: "SOC 2 and GDPR compliance requirements",
      tags: ["security", "compliance", "SOC2", "GDPR"],
      category: "Legal",
    },
    folderId: "folder-legal",
    folderPath: "/Legal/Compliance",
    owner: mockUsers[0],
    createdAt: "2025-03-15T09:00:00Z",
    createdBy: mockUsers[0],
    updatedAt: "2025-09-30T11:00:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 5,
    isLocked: false,
    checkoutCount: 18,
    downloadCount: 145,
  },
  {
    id: "starred-8",
    objectId: "0900000180002008",
    name: "Customer Onboarding Video.mp4",
    type: "video",
    mimeType: "video/mp4",
    extension: "mp4",
    size: 245678901,
    status: "published",
    metadata: {
      title: "Customer Onboarding Video",
      description: "Welcome video for new customers",
      tags: ["video", "onboarding", "customer", "training"],
      category: "Customer Success",
    },
    folderId: "folder-cs",
    folderPath: "/Customer Success/Training",
    owner: mockUsers[1],
    createdAt: "2025-07-10T13:00:00Z",
    createdBy: mockUsers[1],
    updatedAt: "2025-11-05T10:30:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 2,
    isLocked: false,
    checkoutCount: 3,
    downloadCount: 892,
  },
];
