import type { Document, User } from "@/schemas";

const mockUsers: User[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john.doe@company.com",
    avatar: undefined,
    role: "admin",
  },
  {
    id: "user-2",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    avatar: undefined,
    role: "editor",
  },
  {
    id: "user-3",
    name: "Mike Wilson",
    email: "mike.wilson@company.com",
    avatar: undefined,
    role: "viewer",
  },
  {
    id: "user-4",
    name: "Emily Brown",
    email: "emily.brown@company.com",
    avatar: undefined,
    role: "editor",
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc-1",
    objectId: "0900000180001001",
    name: "Q4 2025 Financial Report.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    extension: "pdf",
    size: 2457600,
    status: "published",
    metadata: {
      title: "Q4 2025 Financial Report",
      description: "Quarterly financial summary for Q4 2025",
      tags: ["finance", "quarterly", "2025"],
      category: "Financial",
    },
    folderId: "folder-1",
    folderPath: "/Financial Records/2025",
    owner: mockUsers[0],
    createdAt: "2025-12-15T10:30:00Z",
    createdBy: mockUsers[0],
    updatedAt: "2026-01-10T14:22:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 3,
    isLocked: false,
    checkoutCount: 5,
    downloadCount: 42,
  },
  {
    id: "doc-2",
    objectId: "0900000180001002",
    name: "Marketing Strategy 2026.pptx",
    type: "presentation",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    extension: "pptx",
    size: 8912345,
    status: "pending_review",
    metadata: {
      title: "Marketing Strategy 2026",
      description: "Annual marketing strategy and campaign plans",
      tags: ["marketing", "strategy", "2026"],
      category: "Marketing",
    },
    folderId: "folder-2",
    folderPath: "/Projects/Marketing Assets",
    owner: mockUsers[1],
    createdAt: "2026-01-05T09:15:00Z",
    createdBy: mockUsers[1],
    updatedAt: "2026-01-12T16:45:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 2,
    isLocked: true,
    lockedBy: mockUsers[1],
    lockedAt: "2026-01-12T16:45:00Z",
    checkoutCount: 3,
    downloadCount: 15,
  },
  {
    id: "doc-3",
    objectId: "0900000180001003",
    name: "Employee Handbook v4.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    extension: "docx",
    size: 1234567,
    status: "approved",
    metadata: {
      title: "Employee Handbook",
      description: "Company policies and procedures",
      tags: ["hr", "handbook", "policies"],
      category: "HR",
    },
    folderId: "folder-3",
    folderPath: "/HR Documents",
    owner: mockUsers[3],
    createdAt: "2024-06-20T11:00:00Z",
    createdBy: mockUsers[3],
    updatedAt: "2025-11-30T09:20:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 4,
    isLocked: false,
    checkoutCount: 12,
    downloadCount: 156,
  },
  {
    id: "doc-4",
    objectId: "0900000180001004",
    name: "Product Mockups.zip",
    type: "archive",
    mimeType: "application/zip",
    extension: "zip",
    size: 45678912,
    status: "draft",
    metadata: {
      title: "Product Mockups",
      description: "UI/UX mockups for new product features",
      tags: ["design", "mockups", "product"],
      category: "Design",
    },
    folderId: "folder-2",
    folderPath: "/Projects/Client Proposals",
    owner: mockUsers[2],
    createdAt: "2026-01-08T14:30:00Z",
    createdBy: mockUsers[2],
    updatedAt: "2026-01-08T14:30:00Z",
    updatedBy: mockUsers[2],
    currentVersion: 1,
    isLocked: false,
    checkoutCount: 0,
    downloadCount: 2,
  },
  {
    id: "doc-5",
    objectId: "0900000180001005",
    name: "Budget Analysis 2026.xlsx",
    type: "spreadsheet",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    extension: "xlsx",
    size: 567890,
    status: "published",
    metadata: {
      title: "Budget Analysis 2026",
      description: "Annual budget breakdown and projections",
      tags: ["finance", "budget", "2026"],
      category: "Financial",
    },
    folderId: "folder-1",
    folderPath: "/Financial Records/2026",
    owner: mockUsers[0],
    createdAt: "2025-12-01T08:00:00Z",
    createdBy: mockUsers[0],
    updatedAt: "2026-01-11T11:15:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 5,
    isLocked: false,
    checkoutCount: 8,
    downloadCount: 67,
  },
  {
    id: "doc-6",
    objectId: "0900000180001006",
    name: "Product Demo Video.mp4",
    type: "video",
    mimeType: "video/mp4",
    extension: "mp4",
    size: 125678901,
    status: "approved",
    metadata: {
      title: "Product Demo Video",
      description: "Demo video for new product launch",
      tags: ["video", "demo", "marketing"],
      category: "Marketing",
    },
    folderId: "folder-2",
    folderPath: "/Projects/Marketing Assets",
    owner: mockUsers[1],
    createdAt: "2025-11-15T13:45:00Z",
    createdBy: mockUsers[2],
    updatedAt: "2025-12-20T10:30:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 2,
    isLocked: false,
    checkoutCount: 2,
    downloadCount: 89,
  },
  {
    id: "doc-7",
    objectId: "0900000180001007",
    name: "Legal Contract Template.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    extension: "docx",
    size: 234567,
    status: "published",
    metadata: {
      title: "Legal Contract Template",
      description: "Standard contract template for vendors",
      tags: ["legal", "contract", "template"],
      category: "Legal",
    },
    folderId: "folder-4",
    folderPath: "/Legal Documents/Contracts",
    owner: mockUsers[3],
    createdAt: "2024-03-10T09:00:00Z",
    createdBy: mockUsers[3],
    updatedAt: "2025-09-15T14:00:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 6,
    isLocked: false,
    checkoutCount: 25,
    downloadCount: 234,
  },
  {
    id: "doc-8",
    objectId: "0900000180001008",
    name: "Brand Guidelines.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    extension: "pdf",
    size: 15678901,
    status: "published",
    metadata: {
      title: "Brand Guidelines",
      description: "Official brand guidelines and assets",
      tags: ["brand", "guidelines", "design"],
      category: "Marketing",
    },
    folderId: "folder-2",
    folderPath: "/Projects/Marketing Assets",
    owner: mockUsers[1],
    createdAt: "2024-01-20T10:00:00Z",
    createdBy: mockUsers[1],
    updatedAt: "2025-06-10T16:30:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 3,
    isLocked: false,
    checkoutCount: 4,
    downloadCount: 312,
  },
  {
    id: "doc-9",
    objectId: "0900000180001009",
    name: "Team Photo Gallery.jpg",
    type: "image",
    mimeType: "image/jpeg",
    extension: "jpg",
    size: 4567890,
    status: "approved",
    metadata: {
      title: "Team Photo Gallery",
      description: "Company team photos from annual event",
      tags: ["photos", "team", "event"],
      category: "HR",
    },
    folderId: "folder-3",
    folderPath: "/HR Documents",
    owner: mockUsers[3],
    createdAt: "2025-10-05T15:00:00Z",
    createdBy: mockUsers[3],
    updatedAt: "2025-10-05T15:00:00Z",
    updatedBy: mockUsers[3],
    currentVersion: 1,
    isLocked: false,
    checkoutCount: 0,
    downloadCount: 45,
  },
  {
    id: "doc-10",
    objectId: "0900000180001010",
    name: "Compliance Report 2025.pdf",
    type: "pdf",
    mimeType: "application/pdf",
    extension: "pdf",
    size: 3456789,
    status: "archived",
    metadata: {
      title: "Compliance Report 2025",
      description: "Annual compliance and audit report",
      tags: ["compliance", "audit", "2025"],
      category: "Legal",
    },
    folderId: "folder-4",
    folderPath: "/Legal Documents/Compliance",
    owner: mockUsers[0],
    createdAt: "2025-12-31T17:00:00Z",
    createdBy: mockUsers[0],
    updatedAt: "2026-01-05T09:00:00Z",
    updatedBy: mockUsers[0],
    currentVersion: 1,
    isLocked: false,
    checkoutCount: 1,
    downloadCount: 23,
  },
  {
    id: "doc-11",
    objectId: "0900000180001011",
    name: "Meeting Notes - Jan 2026.docx",
    type: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    extension: "docx",
    size: 89012,
    status: "draft",
    metadata: {
      title: "Meeting Notes - January 2026",
      description: "Weekly team meeting notes",
      tags: ["meetings", "notes", "2026"],
      category: "General",
    },
    folderId: "folder-1",
    folderPath: "/Projects/Q4 Reports",
    owner: mockUsers[2],
    createdAt: "2026-01-13T10:00:00Z",
    createdBy: mockUsers[2],
    updatedAt: "2026-01-13T11:30:00Z",
    updatedBy: mockUsers[2],
    currentVersion: 1,
    isLocked: true,
    lockedBy: mockUsers[2],
    lockedAt: "2026-01-13T11:30:00Z",
    checkoutCount: 1,
    downloadCount: 0,
  },
  {
    id: "doc-12",
    objectId: "0900000180001012",
    name: "Podcast Episode 15.mp3",
    type: "audio",
    mimeType: "audio/mpeg",
    extension: "mp3",
    size: 67890123,
    status: "published",
    metadata: {
      title: "Podcast Episode 15",
      description: "Company podcast - Industry Trends",
      tags: ["podcast", "audio", "marketing"],
      category: "Marketing",
    },
    folderId: "folder-2",
    folderPath: "/Projects/Marketing Assets",
    owner: mockUsers[1],
    createdAt: "2025-12-10T12:00:00Z",
    createdBy: mockUsers[1],
    updatedAt: "2025-12-10T14:00:00Z",
    updatedBy: mockUsers[1],
    currentVersion: 1,
    isLocked: false,
    checkoutCount: 0,
    downloadCount: 178,
  },
];
